#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 [build|test|<path to main>]"
    exit
fi

# Always build afresh
echo "Building..."
rm -rf build
kotlinc -cp $(ls -1 ./jars/* | paste -s -d: -) -Xcontext-parameters -d build src/*

if [[ "$1" == "test" ]]; then
    echo "Running tests..."
    echo
    kotlin ./jars/junit-platform-console-standalone-*.jar execute -cp build --scan-class-path
elif [[ "$1" == "build" ]]; then
    exit
else
    echo "Running $1..."
    echo
    kotlin -cp build $1
fi