#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 [build|test|<path to main>]"
    exit
fi

# Always build afresh
echo "Building..."
rm -rf build
kotlinc -cp $(ls -1 ./jars/* | paste -s -d: -) -Xcontext-parameters -d build src/*

if [[ "$1" == "test" ]]; then
    shift
    echo "Running tests..."
    echo
    # https://docs.junit.org/6.0.3/running-tests/console-launcher.html
    kotlin ./jars/junit-platform-console-standalone-*.jar execute -cp build --scan-class-path -e junit-jupiter $@
elif [[ "$1" == "build" ]]; then
    exit
else
    echo "Running $1..."
    echo
    kotlin -cp build $1
fi