#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Usage: $0 [build|test|<path to main>]"
    exit
fi

# Always build afresh
CLASSPATH=$(ls -1 ./jars/* /opt/homebrew/Cellar/kotlin/*/libexec/lib/kotlin{-test,-test-junit5,-stdlib,x-coroutines-core-jvm}.jar | paste -s -d: -)
echo "Building with classpath $CLASSPATH"
rm -rf build
kotlinc -cp $CLASSPATH -Xcontext-parameters -d build src/*

if [[ "$1" == "test" ]]; then
    shift
    echo "Running tests..."
    echo
    # https://docs.junit.org/6.0.3/running-tests/console-launcher.html
    kotlin ./jars/junit-platform-console-standalone-*.jar execute -cp build:$CLASSPATH -e junit-jupiter --scan-class-path $@
elif [[ "$1" == "build" ]]; then
    exit
else
    echo "Running $@..."
    echo
    kotlin -cp build $@
fi